import type { Metadata } from 'next';
import { Sidebar, SidebarBody, SidebarLink } from '@/components/ui/sidebar';
import { IconHome, IconUser } from '@tabler/icons-react';

// Métadonnées optionnelles
export const metadata: Metadata = {
    title: 'Dashboard BVML - Admin',
    description: 'Generated by create next app',
};

export default function AdminLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    // Exemple de liens que tu souhaites afficher dans ta sidebar
    const links = [
        {
            label: 'Accueil',
            href: '/', // ou /administration/home, etc.
            icon: <IconHome />,
        },
        {
            label: 'Utilisateurs',
            href: '/administration/users',
            icon: <IconUser />,
        },
        // Ajoute ici d'autres liens
    ];

    return (
        <div className='relative'>
            {/* Sidebar */}
            <div className='absolute top-0 left-0 h-full z-50'>
                <Sidebar>
                    <SidebarBody>
                        {/* On parcourt les liens et on utilise SidebarLink */}
                        {links.map((link) => (
                            <SidebarLink key={link.href} link={link} />
                        ))}
                    </SidebarBody>
                </Sidebar>
            </div>

            {/* Contenu principal */}
            <main className='mx-20'>{children}</main>
        </div>
    );
}
